on:
  push:
    branches: [ production ]


name: Build and deploy services

env:
  REGION: europe-west1
  GCR_URL: gcr.io/${{ secrets.GCP_PROJECT }}

jobs:
  deploy-frontend:
    environment: Production
    runs-on: ubuntu-latest
    steps:
    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and push frontend
      env:
        IMAGE_NAME: ${{ env.GCR_URL }}/${{ secrets.GCP_SERVICE_FRONTEND }}:${{ github.sha }}
      run: |-
        docker build -t $IMAGE_NAME frontend/
        docker push $IMAGE_NAME

    - name: Deploy frontend to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v0.2.0
      env:
        IMAGE_NAME: ${{ env.GCR_URL }}/${{ secrets.GCP_SERVICE_FRONTEND }}:${{ github.sha }}
      with:
        service: ${{ secrets.GCP_SERVICE_FRONTEND }}
        image: ${{ env.IMAGE_NAME }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}
        region: ${{ env.REGION }}

  deploy-backend:
    environment: Production
    runs-on: ubuntu-latest
    steps:
    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and push backend
      env:
        IMAGE_NAME: ${{ env.GCR_URL }}/${{ secrets.GCP_SERVICE_BACKEND }}:${{ github.sha }}
      run: |-
        docker build -t $IMAGE_NAME backend/
        docker push $IMAGE_NAME

    - name: Deploy backend to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v0.2.0
      env:
        IMAGE_NAME: ${{ env.GCR_URL }}/${{ secrets.GCP_SERVICE_BACKEND }}:${{ github.sha }}
      with:
        service: ${{ secrets.GCP_SERVICE_BACKEND }}
        image: ${{ env.IMAGE_NAME }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}
        region: ${{ env.REGION }}
